### ISSUE TITLE
Previous Game Flashbacks in New Game

### ISSUE THREAD

**Issue by LoveOken** [LoveOken/avalon.ist#20]
After finishing a game, if you make a new game you get flashbacks from the previous game.
 
 I think this has something to do with the sockets updating a room they are not supposed to update.
 
 Check afterGameSave.js and beforeGame.js for problems

**Comment by LoveOken** [comment]
This seems to be solved, there are no reports of it happening again

In any case this will be open in case it happens again

**Comment by DolceTriade** [comment]
Let's close these out and allow pepole to report again if they see it.
